name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel build-essential git libncurses5
        pip install --upgrade pip Cython virtualenv

    - name: Install Buildozer
      run: |
        git clone https://github.com/kivy/buildozer.git
        cd buildozer
        sudo python3 setup.py install

    - name: Initialize .buildozer dir (needed for caching)
      run: |
        mkdir -p .buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3.1.3
      with:
        name: my-kivy-app
        path: bin/*.apk
